apiVersion: v1
kind: Service
metadata:
  name: blog-web-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: blog
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 5000